### ISSUE TITLE
Swagger misconfigured

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-cloud#25]
`org.killbill.server.baseUrl` defaults to `http://localhost:8080` in the Docker image -- it should somehow be set to the `docker-machine` ip address instead.

**Comment by pierre** [comment]
This is mainly a research task, if somehow the container can access its host IP (as returned by `docker-machine inspect default -f '{{.Driver.IPAddress}}'`, e.g. 192.168.99.100). Or maybe we can somehow pass it automatically when running `docker run`?

If there is a way, besides fixing Swagger, we should also fix the default `java.rmi.server.hostname` JMX property which is defined here: https://github.com/killbill/killbill-cloud/blob/7e00ff8fcf0179933a255478b5dd35897f426514/ansible/templates/tomcat/conf/setenv.sh.j2#L45

The value returned today for `inventory_hostname` is `localhost` (incorrect for `java.rmi.server.hostname` as `jconsole` expects the host IP).

**Comment by wwjbatista** [comment]
@pierre, these are my findings (I do not use docker-machine, since my environment OS is Ubuntu ):

What I could find for letting the container know the IP of the host is by adding the IP into the host file in the container as described here (https://docs.docker.com/engine/reference/run/#network-settings). This is a blog that talk about the same: `https://biancatamayo.me/blog/2017/11/03/docker-add-host-ip/`. I tried this approach but with no avail; this is the command that was run `docker run --add-host="out:10.100.3.133" -it killbill/killbill:latest`. The IP was retrieved with `Docker inspect`. But this approach will set a `hostname` (out), and will not work for the `-Djava.rmi.server.hostname property`.

Other approaches that I tried (expeciffically for the `-Djava.rmi.server.hostname `property fix) were:
1-	Replace the `inventory_hostname` with `hostvars[inventory_hostname]['ansible_default_ipv4']['address']`. This will set it with the IP.
2-	On the `Dockerfile` replace the `localhost` of the `ANSIBLE_OPTS` with the actual `Host IP`.  

I am leaving my research here since digging more will require from my part to configure a new environment that will use `docker machine`, and will take more than one day. 

Please advise what would be the next steps to take for this issue.
