### ISSUE TITLE
Environment variables in README different from docker compose files

### ISSUE THREAD

**Issue by lungati** [killbill/killbill-cloud#80]
The README file has different environment variables compared to the docker compose files:

README:
      KILLBILL_CONFIG_DAO_URL:          jdbc:h2:file:/var/lib/killbill/killbill;MODE=MYSQLDB_CLOSE_DELAY=-1;MVCC=true;DB_CLOSE_ON_EXIT=FALSE
      KILLBILL_CONFIG_DAO_USER:         killbill
      KILLBILL_CONFIG_DAO_PASSWORD:     killbill

docker compose (docker-compose.kb.yml):
    - KILLBILL_CONFIG_DAO_URL=jdbc:mysql://db:3306/killbill
    - KILLBILL_CONFIG_DAO_USER=root
    - KILLBILL_CONFIG_DAO_PASSWORD=killbill

**Comment by pierre** [comment]
This is by design: the README shows the default values (setup that doesn't require any dependency like a MySQL database). The values from the docker-compose file are set to work with a specific setup (assumes a MySQL container).

Please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) for implementation questions.
